### ISSUE TITLE
panic: interface conversion: *CloudForest.AdaBoostTarget is not CloudForest.BoostingTarget: missing method Boost

### ISSUE THREAD

**Issue by pebbe** [ryanbressler/CloudForest#59]
When running `growforest` with option `-adaboost` I get:
```
panic: interface conversion: *CloudForest.AdaBoostTarget is not CloudForest.BoostingTarget: missing method Boost

goroutine 1 [running]:
main.main.func1()
        [...]/github.com/ryanbressler/CloudForest/growforest/growforest.go:683 +0x1763
main.main()
        [...]/github.com/ryanbressler/CloudForest/growforest/growforest.go:748 +0x2673
```

**Comment by ryanbressler** [comment]
Oh darn i broke that in a recent update, will try to find a chance to fix it soon.
